# Generated by Django 6.0 on 2026-01-12 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id_cancion', models.AutoField(primary_key=True, serialize=False)),
                ('id_spotify', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('artistas', models.CharField(max_length=300)),
                ('album', models.CharField(blank=True, max_length=200, null=True)),
                ('duracion_ms', models.IntegerField()),
                ('popularidad', models.IntegerField(blank=True, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'canciones',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id_playlist', models.AutoField(primary_key=True, serialize=False)),
                ('id_spotify', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('total_canciones', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_importo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'playlists',
            },
        ),
        migrations.CreateModel(
            name='PlaylistCancion',
            fields=[
                ('id_relacion', models.AutoField(primary_key=True, serialize=False)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('fecha_agregado', models.DateTimeField(blank=True, null=True)),
                ('agregado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.cancion')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playlists.playlist')),
            ],
            options={
                'db_table': 'playlist_canciones',
                'unique_together': {('playlist', 'cancion')},
            },
        ),
    ]
