# Generated by Django 6.0 on 2026-01-12 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cancion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playlistcancion',
            options={'managed': False},
        ),
    ]
