# Generated by Django 5.2.10 on 2026-05-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_alter_cancion_options_alter_playlist_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id_tarea', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ejecucion', models.DateTimeField()),
                ('intentos', models.IntegerField(default=0)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('url_cancion', models.TextField(blank=True, null=True)),
                ('posicion', models.IntegerField(blank=True, null=True)),
                ('posicion_anterior', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tareas',
                'managed': False,
            },
        ),
    ]
