# Generated by Django 5.2.10 on 2026-05-10 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('token_sesion', models.CharField(max_length=255)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('ip_origen', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'sesiones',
                'managed': False,
            },
        ),
    ]
