# Generated by Django 6.0 on 2026-01-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexion', '0002_spotifyauth'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredencialesSpotify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(default='Bearer', max_length=20)),
                ('scope', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'spotify_token',
            },
        ),
        migrations.DeleteModel(
            name='SpotifyAuth',
        ),
    ]
