# Generated by Django 6.0 on 2026-01-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexion', '0003_credencialesspotify_delete_spotifyauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='credencialesspotify',
            name='rate_limit_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
