# Generated by Django 5.2.10 on 2026-05-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conexion', '0004_credencialesspotify_rate_limit_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credencialesspotify',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
