# Generated by Django 5.2.10 on 2026-05-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEvento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('nivel', models.CharField(max_length=16)),
                ('usuario', models.CharField(max_length=128)),
                ('modulo', models.CharField(max_length=128)),
                ('mensaje', models.TextField()),
            ],
            options={
                'db_table': 'logs_eventos',
                'managed': False,
            },
        ),
    ]
