"""
Django settings for syncronify project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

import environ
import os

# Inicializar entorno
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Variables de Spotify
SPOTIFY_CLIENT_ID = env("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = env("SPOTIFY_CLIENT_SECRET")
SPOTIFY_API_BASE = env("SPOTIFY_API_BASE", default="https://api.spotify.com/v1")
SPOTIFY_TOKEN_URL = env("SPOTIFY_TOKEN_URL", default="https://accounts.spotify.com/api/token")
# Variables de Spotify adicionales
SPOTIFY_REDIRECT_URI = env("SPOTIFY_REDIRECT_URI", default="https://127.0.0.1:8000/spotify/callback")
SPOTIFY_AUTH_URL = env("SPOTIFY_AUTH_URL", default="https://accounts.spotify.com/authorize")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dka8o=229*iy&02%0-s&&dqlq&yw4vo&gz^3*@0g_h^^^6g0ny'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django_extensions",
    'django_celery_beat',
    'conexion',
    'importar',
    'lista_playlist',
    'editar_playlist',
    "sincronizar_playlist",
    'logs',
    'playlists.apps.PlaylistsConfig',
    'usuarios.apps.UsuariosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'usuarios.middleware.ValidarSesionMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'syncronify.urls'

MESSAGE_STORAGE = "logs.storage.LogStorage"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # carpeta global de templates
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # carpeta global de archivos estáticos
]


WSGI_APPLICATION = 'syncronify.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = { 
    'default': { 
        'ENGINE': 'django.db.backends.postgresql', 
        'NAME': 'syncronify_db', 
        'USER': 'postgres', 
        'PASSWORD': 'Newloger123', 
        'HOST': 'localhost', 
        'PORT': '5432', 
    }
}

# settings.py
AUTH_USER_MODEL = "usuarios.Usuario"


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Caracas' 
USE_TZ = True

USE_I18N = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'


# URL de login por defecto (usada por @login_required)
LOGIN_URL = 'login'

# URL a la que se redirige después de un login exitoso
LOGIN_REDIRECT_URL = 'lista_playlist_home'

# URL a la que se redirige después de un logout
LOGOUT_REDIRECT_URL = 'login'

# Tiempo de vida de la cookie de sesión (en segundos)
# 2 semanas (1209600 segundos)
SESSION_COOKIE_AGE = 1209600  

# Si quieres que la sesión se borre al cerrar el navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # pon True si prefieres que se cierre

# Seguridad extra
SESSION_COOKIE_SECURE = False  # pon True en producción con HTTPS
CSRF_COOKIE_SECURE = False     # igual que arriba


